/**
 * Regenerate the data-safety fixtures for the CURRENT schema versions.
 * Part of the release checklist: run after any schema bump, commit the
 * new files, never edit or delete the old versions (they are the matrix).
 *
 *   pnpm run make:fixture            # every kind, after a physical schema bump
 *   pnpm run make:fixture -- --only export   # only the export envelope (a JSON-only change)
 *
 * The fixtures are a version matrix: a new export version whose database
 * structures did not change (week 11) must not rewrite the shipped
 * IndexedDB/SQLite fixtures, so `--only` limits what is generated.
 *
 * Writes:
 *   tests/fixtures/export/v<EXPORT_SCHEMA_VERSION>.json   — an export envelope
 *   tests/fixtures/idb/v<INDEXEDDB_SCHEMA_VERSION>.json   — raw Dexie rows per store
 *   tests/fixtures/sqlite/v<SQLITE_SCHEMA_VERSION>.sql      — a SQL dump at that schema version
 *   tests/fixtures/db/v<SQLITE_SCHEMA_VERSION>.db           — that dump loaded into a real SQLite file
 *
 * Generated in UTC on every machine: the seeded world builds its timestamps from local wall
 * time, and CI regenerates the fixtures to prove they are current, so a UTC+3 developer
 * machine and the UTC runner must produce the same bytes.
 */
process.env.TZ = 'UTC';

import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { fixedClock, seedWorld } from '@orbit/core';
import type { BaseRecord } from '@orbit/core';
import {
  EXPORT_SCHEMA_VERSION,
  INDEXEDDB_SCHEMA_VERSION,
  MIGRATIONS,
  SQLITE_SCHEMA_VERSION,
  STORE_ORDER,
  createMemoryRepository,
  exportJson,
  serializeExport,
} from '@orbit/storage';
import type { EntityStore } from '@orbit/storage';
import { betterSqliteDriver } from '@orbit/storage/test/betterSqliteDriver';

const KINDS = ['export', 'idb', 'sqlite'] as const;
type Kind = (typeof KINDS)[number];
const onlyArg = process.argv.indexOf('--only');
const only = new Set<Kind>(
  onlyArg === -1
    ? KINDS
    : process.argv
        .slice(onlyArg + 1)
        .filter((a): a is Kind => (KINDS as readonly string[]).includes(a)),
);
if (!only.size) {
  console.error(`usage: make-fixture [--only ${KINDS.join('|')} ...]`);
  process.exit(1);
}

const clock = fixedClock('2026-09-12T09:00:00.000Z');
const world = seedWorld({
  seed: 2026,
  sizes: { tasks: 60, notes: 12, events: 6, people: 5, days: 7 },
});

const repo = createMemoryRepository({ clock });
await repo.transaction(async (tx) => {
  for (const name of STORE_ORDER) {
    const store = tx[name] as unknown as EntityStore<BaseRecord>;
    for (const rec of world[name]) await store.upsert(rec, { preserveUpdatedAt: true });
  }
});

const written: string[] = [];
const envelope = await exportJson(repo, clock);

if (only.has('export')) {
  mkdirSync('tests/fixtures/export', { recursive: true });
  const exportPath = `tests/fixtures/export/v${EXPORT_SCHEMA_VERSION}.json`;
  writeFileSync(exportPath, serializeExport(envelope) + '\n');
  written.push(exportPath);
}

if (only.has('idb')) {
  mkdirSync('tests/fixtures/idb', { recursive: true });
  const stores: Record<string, BaseRecord[]> = {};
  for (const name of STORE_ORDER) stores[name] = envelope.data[name];
  const idbPath = `tests/fixtures/idb/v${INDEXEDDB_SCHEMA_VERSION}.json`;
  writeFileSync(
    idbPath,
    JSON.stringify({ schemaVersion: INDEXEDDB_SCHEMA_VERSION, stores }, null, 2) + '\n',
  );
  written.push(idbPath);
}

if (only.has('sqlite')) {
  mkdirSync('tests/fixtures/sqlite', { recursive: true });
  // SQLite dump: the schema as shipped at this version plus every row.
  const q = (v: string) => `'${v.replace(/'/g, "''")}'`;
  const sqlLines: string[] = [
    `-- Orbit SQLite fixture, schema version ${SQLITE_SCHEMA_VERSION}. Generated by scripts/make-fixture.ts.`,
    ...MIGRATIONS.filter((m) => m.version <= SQLITE_SCHEMA_VERSION).map((m) => m.sql),
    `PRAGMA user_version = ${SQLITE_SCHEMA_VERSION};`,
  ];
  for (const name of STORE_ORDER) {
    for (const rec of envelope.data[name]) {
      sqlLines.push(
        `INSERT INTO ${name}(id, data) VALUES (${q(rec.id)}, ${q(JSON.stringify(rec))});`,
      );
    }
  }
  const sqlPath = `tests/fixtures/sqlite/v${SQLITE_SCHEMA_VERSION}.sql`;
  const sql = sqlLines.join('\n') + '\n';
  writeFileSync(sqlPath, sql);
  written.push(sqlPath);

  // The same dump as a real database file, exactly as that version of Orbit would have
  // written it. Rollback journal mode (the default), not WAL, so the file stands alone and
  // the bytes are reproducible: the desktop matrix opens and migrates these.
  mkdirSync('tests/fixtures/db', { recursive: true });
  const dbPath = `tests/fixtures/db/v${SQLITE_SCHEMA_VERSION}.db`;
  rmSync(dbPath, { force: true });
  const driver = betterSqliteDriver(dbPath);
  await driver.exec(sql);
  await driver.close();
  written.push(dbPath);
}

const total = STORE_ORDER.reduce((n, name) => n + envelope.data[name].length, 0);
console.log(`wrote ${written.join(', ')} (${total} records)`);
